<?php

return [
  'eway_recurring_contribution_max_retry' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_contribution_max_fail_attempts',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '3',
    'description' => 'Maximum number of retries for failed eWay recurring contributions.',
    'title' => 'Maximum Number of Retries',
    'help_text' => 'Maximum number of retries for failed eWay recurring contributions.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_recurring_contribution_retry_delay' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_contribution_retry_delay',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '4',
    'description' => 'Number of days after CiviCRM should retry recurring payment.',
    'title' => 'Retry delay (in days)',
    'help_text' => 'Number of days after CiviCRM should retry recurring payment.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_recurring_keep_sending_receipts' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_keep_sending_receipts',
    'type' => 'Boolean',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '0',
    'description' => 'Whether to keep sending CiviCRM receipt/invoice after initial contribution. User will continue to receive receipts from eWay regardless of this setting.',
    'title' => 'Send receipt for all recurring contributions',
    'help_text' => 'Whether to keep sending CiviCRM receipt/invoice after initial contribution. User will continue to receive receipts from eWay regardless of this setting.',
    'html_type' => 'checkbox',
    'quick_form_type' => 'YesNo',
  ],
  'eway_settlement_window_days' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_settlement_window_days',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '10',
    'description' => 'Settlement sync window, in days back from today. Covers which Completed eWAY contributions are treated as still awaiting reconciliation and how many calendar days of eWAY settlement reports are queried each run. Contributions older than this require standard manual reconciliation.',
    'title' => 'Settlement Sync: Window (days)',
    'help_text' => 'Days back from today for the settlement sync window. Covers both contribution candidacy and the eWAY settlement report date range.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 10,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_settlement_processors' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_settlement_processors',
    // 'Array' (not 'String' + serialize): the settings form writes via APIv3,
    // which flattens arrays for type String into a legacy delimited string and
    // ignores 'serialize'. Type Array is stored/read as an array on every path.
    'type' => 'Array',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => [],
    'title' => 'Settlement Sync: Payment Processors',
    'description' => 'Which eWAY payment processors the settlement sync covers. If none are selected the settlement sync does nothing.',
    'help_text' => 'Select the eWAY payment processors that are configured for settlement reporting on the eWAY side. Leave empty to disable the settlement sync entirely.',
    'html_type' => 'Select',
    'quick_form_type' => 'Select',
    'pseudoconstant' => [
      'callback' => 'CRM_eWAYRecurring_SettlementSync::getSettlementProcessorOptions',
    ],
    'html_attributes' => [
      'multiple' => 'multiple',
      'class' => 'crm-select2 huge',
    ],
  ],
];
