<?php
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /var/www/civicrmmaster/sites/default/files/civicrm/ext/au.com.agileware.ewayrecurring/xml/schema//EwayContributionTransactions.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e435b4bc2b25ed1a50af0ffcb1766554)
 */
/**
 * Database access object for the EwayContributionTransactions entity.
 */
class CRM_eWAYRecurring_DAO_EwayContributionTransactions extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_eway_contribution_transactions';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;
  /**
   * Unique EwayContributionTransactions ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to Contribution
   *
   * @var int unsigned
   */
  public $contribution_id;
  /**
   * FK to PaymentProcessor
   *
   * @var int unsigned
   */
  public $payment_processor_id;
  /**
   * @var text
   */
  public $access_code;
  /**
   * @var text
   */
  public $failed_message;
  /**
   * @var int unsigned
   */
  public $status;
  /**
   * @var int unsigned
   */
  public $tries;
  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_eway_contribution_transactions';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contribution_id', 'civicrm_contribution', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'payment_processor_id', 'civicrm_payment_processor', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Unique EwayContributionTransactions ID'),
          'required' => TRUE,
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('FK to Contribution'),
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
        ],
        'payment_processor_id' => [
          'name' => 'payment_processor_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('FK to PaymentProcessor'),
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
        ],
        'access_code' => [
          'name' => 'access_code',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Access Code'),
          'import' => TRUE,
          'where' => 'civicrm_eway_contribution_transactions.access_code',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'failed_message' => [
          'name' => 'failed_message',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Failed Message'),
          'import' => TRUE,
          'where' => 'civicrm_eway_contribution_transactions.failed_message',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Status'),
          'default' => '0',
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
        ],
        'tries' => [
          'name' => 'tries',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Tries'),
          'default' => '0',
          'table_name' => 'civicrm_eway_contribution_transactions',
          'entity' => 'EwayContributionTransactions',
          'bao' => 'CRM_eWAYRecurring_DAO_EwayContributionTransactions',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'eway_contribution_transactions', $prefix, []);
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'eway_contribution_transactions', $prefix, []);
    return $r;
  }
  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}