name: PHPUnit tests

on:
  push: {}
  workflow_dispatch: {}

jobs:
  phpunit:
    uses: agileware/ci-workflows/.github/workflows/civicrm-phpunit-tests.yml@main
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      EXTENSION_NAME: au.com.agileware.ewayrecurring
